<?php
/**
 * This file is part of the Expression Lab plugin.
 *
 * (c) Anderson Salas <github@andersonsalas.com>
 *
 * See the LICENSE file for license information.
 *
 * @package ExpressionLab
 */

namespace ExpressionLab\Core\Ast;

use ExpressionLab\Core\LanguageEngine;
use Symfony\Component\ExpressionLanguage\Node\Node;

if ( ! defined( 'ABSPATH' ) ) {
	die( 'No direct script access allowed' );
}

/**
 * Show AST node.
 *
 * Evaluates the `show[expression]` special form, forcing the rendering of
 * any silenced visualizations generated by the child expression.
 *
 * @since 1.0.0
 * @internal
 * @package ExpressionLab
 */
class ShowNode extends Node {
	/**
	 * Constructor.
	 *
	 * @since 1.0.0
	 * @internal
	 *
	 * @param Node $expression The child expression node.
	 */
	public function __construct( Node $expression ) {
		parent::__construct( array( 'expression' => $expression ) );
	}

	/**
	 * Evaluates the show operation.
	 *
	 * @since 1.0.0
	 * @internal
	 *
	 * @param array $functions The registered functions.
	 * @param array $values    The evaluation context values.
	 * @return mixed Result of the child expression.
	 */
	public function evaluate( array $functions, array $values ): mixed {
		$engine = LanguageEngine::get();
		$engine->tick();

		$value = $this->nodes['expression']->evaluate( $functions, $values );

		if ( ! $engine->is_interactive_mode() ) {
			$silenced_visualizations = $engine->get_silenced_visualizations();
			foreach ( $silenced_visualizations as $visualization ) {
				if ( ! is_array( $visualization ) || empty( $visualization ) ) {
					continue;
				}
				$engine->add_visualization( $visualization, true );
			}
			$engine->clear_silenced_visualizations();
		}

		return $value;
	}

	/**
	 * Converts the node to its array representation for dumping.
	 *
	 * @since 1.0.0
	 * @internal
	 *
	 * @return array Array representation of the node.
	 */
	public function toArray(): array {
		return array( 'show[', $this->nodes['expression'], ']' );
	}

	/**
	 * Compiles the node into PHP code.
	 *
	 * @since 1.0.0
	 * @internal
	 *
	 * @param \Symfony\Component\ExpressionLanguage\Compiler $compiler The compiler.
	 * @throws \RuntimeException If compilation is attempted.
	 */
	public function compile( \Symfony\Component\ExpressionLanguage\Compiler $compiler ): void {
		throw new \RuntimeException( 'ShowNode compilation is not supported.' );
	}
}
