name: PHP Unit Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test-php:
    name: "PHP ${{ matrix.php }} / WP ${{ matrix.wp }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.2'
            wp: '6.4'
          - php: '8.2'
            wp: 'latest'
          - php: '8.3'
            wp: 'latest'
          - php: '8.4'
            wp: 'latest'
          - php: '8.5'
            wp: 'latest'
          - php: '8.5'
            wp: 'trunk'

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Clone repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Configure PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, json, mysqli
          coverage: none
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Install Subversion (SVN)
        run: sudo apt-get update -y && sudo apt-get install -y subversion

      - name: Install WordPress test suite
        run: |
          bash bin/install-wp-tests.sh \
            wordpress_test \
            root \
            root \
            127.0.0.1 \
            ${{ matrix.wp }}
        env:
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
          WP_CORE_DIR: /tmp/wordpress/

      - name: Run Single-site tests
        run: vendor/bin/phpunit --exclude-group multisite

      - name: Run Multisite tests
        run: WP_MULTISITE=1 vendor/bin/phpunit --exclude-group singlesite